// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: persPhone.proto

package PersonalNumber

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PersPhoneService_CreatePersPhoneNumber_FullMethodName = "/PersonalNumber.PersPhoneService/CreatePersPhoneNumber"
	PersPhoneService_GetPersPhoneNumber_FullMethodName    = "/PersonalNumber.PersPhoneService/GetPersPhoneNumber"
	PersPhoneService_UpdatePersPhoneNumber_FullMethodName = "/PersonalNumber.PersPhoneService/UpdatePersPhoneNumber"
	PersPhoneService_DeletePersPhoneNumber_FullMethodName = "/PersonalNumber.PersPhoneService/DeletePersPhoneNumber"
	PersPhoneService_GetPersPhoneNumbers_FullMethodName   = "/PersonalNumber.PersPhoneService/GetPersPhoneNumbers"
)

// PersPhoneServiceClient is the client API for PersPhoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersPhoneServiceClient interface {
	CreatePersPhoneNumber(ctx context.Context, in *CreatePersPhoneNumberRequest, opts ...grpc.CallOption) (*CreatePersPhoneNumberResponse, error)
	GetPersPhoneNumber(ctx context.Context, in *GetPersPhoneNumberRequest, opts ...grpc.CallOption) (*GetPersPhoneNumberResponse, error)
	UpdatePersPhoneNumber(ctx context.Context, in *UpdatePersPhoneNumberRequest, opts ...grpc.CallOption) (*UpdatePersPhoneNumberResponse, error)
	DeletePersPhoneNumber(ctx context.Context, in *DeletePersPhoneNumberRequest, opts ...grpc.CallOption) (*DeletePersPhoneNumberResponse, error)
	GetPersPhoneNumbers(ctx context.Context, in *GetPersPhoneNumbersRequest, opts ...grpc.CallOption) (*GetPersPhoneNumbersResponse, error)
}

type persPhoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersPhoneServiceClient(cc grpc.ClientConnInterface) PersPhoneServiceClient {
	return &persPhoneServiceClient{cc}
}

func (c *persPhoneServiceClient) CreatePersPhoneNumber(ctx context.Context, in *CreatePersPhoneNumberRequest, opts ...grpc.CallOption) (*CreatePersPhoneNumberResponse, error) {
	out := new(CreatePersPhoneNumberResponse)
	err := c.cc.Invoke(ctx, PersPhoneService_CreatePersPhoneNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persPhoneServiceClient) GetPersPhoneNumber(ctx context.Context, in *GetPersPhoneNumberRequest, opts ...grpc.CallOption) (*GetPersPhoneNumberResponse, error) {
	out := new(GetPersPhoneNumberResponse)
	err := c.cc.Invoke(ctx, PersPhoneService_GetPersPhoneNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persPhoneServiceClient) UpdatePersPhoneNumber(ctx context.Context, in *UpdatePersPhoneNumberRequest, opts ...grpc.CallOption) (*UpdatePersPhoneNumberResponse, error) {
	out := new(UpdatePersPhoneNumberResponse)
	err := c.cc.Invoke(ctx, PersPhoneService_UpdatePersPhoneNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persPhoneServiceClient) DeletePersPhoneNumber(ctx context.Context, in *DeletePersPhoneNumberRequest, opts ...grpc.CallOption) (*DeletePersPhoneNumberResponse, error) {
	out := new(DeletePersPhoneNumberResponse)
	err := c.cc.Invoke(ctx, PersPhoneService_DeletePersPhoneNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persPhoneServiceClient) GetPersPhoneNumbers(ctx context.Context, in *GetPersPhoneNumbersRequest, opts ...grpc.CallOption) (*GetPersPhoneNumbersResponse, error) {
	out := new(GetPersPhoneNumbersResponse)
	err := c.cc.Invoke(ctx, PersPhoneService_GetPersPhoneNumbers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersPhoneServiceServer is the server API for PersPhoneService service.
// All implementations must embed UnimplementedPersPhoneServiceServer
// for forward compatibility
type PersPhoneServiceServer interface {
	CreatePersPhoneNumber(context.Context, *CreatePersPhoneNumberRequest) (*CreatePersPhoneNumberResponse, error)
	GetPersPhoneNumber(context.Context, *GetPersPhoneNumberRequest) (*GetPersPhoneNumberResponse, error)
	UpdatePersPhoneNumber(context.Context, *UpdatePersPhoneNumberRequest) (*UpdatePersPhoneNumberResponse, error)
	DeletePersPhoneNumber(context.Context, *DeletePersPhoneNumberRequest) (*DeletePersPhoneNumberResponse, error)
	GetPersPhoneNumbers(context.Context, *GetPersPhoneNumbersRequest) (*GetPersPhoneNumbersResponse, error)
	mustEmbedUnimplementedPersPhoneServiceServer()
}

// UnimplementedPersPhoneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPersPhoneServiceServer struct {
}

func (UnimplementedPersPhoneServiceServer) CreatePersPhoneNumber(context.Context, *CreatePersPhoneNumberRequest) (*CreatePersPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePersPhoneNumber not implemented")
}
func (UnimplementedPersPhoneServiceServer) GetPersPhoneNumber(context.Context, *GetPersPhoneNumberRequest) (*GetPersPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersPhoneNumber not implemented")
}
func (UnimplementedPersPhoneServiceServer) UpdatePersPhoneNumber(context.Context, *UpdatePersPhoneNumberRequest) (*UpdatePersPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePersPhoneNumber not implemented")
}
func (UnimplementedPersPhoneServiceServer) DeletePersPhoneNumber(context.Context, *DeletePersPhoneNumberRequest) (*DeletePersPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePersPhoneNumber not implemented")
}
func (UnimplementedPersPhoneServiceServer) GetPersPhoneNumbers(context.Context, *GetPersPhoneNumbersRequest) (*GetPersPhoneNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersPhoneNumbers not implemented")
}
func (UnimplementedPersPhoneServiceServer) mustEmbedUnimplementedPersPhoneServiceServer() {}

// UnsafePersPhoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersPhoneServiceServer will
// result in compilation errors.
type UnsafePersPhoneServiceServer interface {
	mustEmbedUnimplementedPersPhoneServiceServer()
}

func RegisterPersPhoneServiceServer(s grpc.ServiceRegistrar, srv PersPhoneServiceServer) {
	s.RegisterService(&PersPhoneService_ServiceDesc, srv)
}

func _PersPhoneService_CreatePersPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersPhoneServiceServer).CreatePersPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersPhoneService_CreatePersPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersPhoneServiceServer).CreatePersPhoneNumber(ctx, req.(*CreatePersPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersPhoneService_GetPersPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersPhoneServiceServer).GetPersPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersPhoneService_GetPersPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersPhoneServiceServer).GetPersPhoneNumber(ctx, req.(*GetPersPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersPhoneService_UpdatePersPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePersPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersPhoneServiceServer).UpdatePersPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersPhoneService_UpdatePersPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersPhoneServiceServer).UpdatePersPhoneNumber(ctx, req.(*UpdatePersPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersPhoneService_DeletePersPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePersPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersPhoneServiceServer).DeletePersPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersPhoneService_DeletePersPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersPhoneServiceServer).DeletePersPhoneNumber(ctx, req.(*DeletePersPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersPhoneService_GetPersPhoneNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersPhoneNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersPhoneServiceServer).GetPersPhoneNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PersPhoneService_GetPersPhoneNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersPhoneServiceServer).GetPersPhoneNumbers(ctx, req.(*GetPersPhoneNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersPhoneService_ServiceDesc is the grpc.ServiceDesc for PersPhoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersPhoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PersonalNumber.PersPhoneService",
	HandlerType: (*PersPhoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePersPhoneNumber",
			Handler:    _PersPhoneService_CreatePersPhoneNumber_Handler,
		},
		{
			MethodName: "GetPersPhoneNumber",
			Handler:    _PersPhoneService_GetPersPhoneNumber_Handler,
		},
		{
			MethodName: "UpdatePersPhoneNumber",
			Handler:    _PersPhoneService_UpdatePersPhoneNumber_Handler,
		},
		{
			MethodName: "DeletePersPhoneNumber",
			Handler:    _PersPhoneService_DeletePersPhoneNumber_Handler,
		},
		{
			MethodName: "GetPersPhoneNumbers",
			Handler:    _PersPhoneService_GetPersPhoneNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persPhone.proto",
}
